# Generated by Django 4.2.4 on 2023-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='static/images/default_profile.png', upload_to=''),
        ),
    ]
