# Generated by Django 4.2.7 on 2023-11-08 20:48

from django.db import migrations

def add_permissions(apps,schema_migration):
    Group=apps.get_model('auth','Group')
    Permission=apps.get_model('auth','Permission')
    add_blog=Permission.objects.get(codename='add_blog')
    change_blog=Permission.objects.get(codename='change_blog')
    delete_blog=Permission.objects.get(codename='delete_blog')
    view_blog=Permission.objects.get(codename='view_blog')
    creator_permissions=[
        add_blog,
        change_blog,
        delete_blog,
        view_blog,
    ]
    creators=Group.objects.get(name='creators')
    creators.permissions.set(creator_permissions)
    subscriber=Group.objects.get(name='subscribers')
    subscriber.permissions.add(view_blog)
    
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_word_count'),
    ]



    operations = [
        migrations.RunPython(add_permissions)
    ]
