# Generated by Django 4.2.7 on 2023-11-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231108_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', "Peut changer le titre d'un billet de blog")]},
        ),
    ]
