# Generated by Django 4.2.7 on 2023-11-09 11:55

from django.db import migrations

def data_migrations(apps,schema_migration):
    blogs=apps.get_model('blog','Blog')
    for blog in blogs.objects.all():
        blog.contributors.add(blog.author,through_defaults={'contribution':'Auteur principal'})



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(data_migrations)
    ]
